# ======================================================================
# SPRING CLOUD CONSUL CONFIGURATION
# ======================================================================

server:
  port: 8072
myapp:
  allowedIps:
    - 192.168.1.100
    - 10.0.0.1
    - 0:0:0:0:0:0:0:1
  denied-ips:
    - 10.0.0.1
    - 0:0:0:0:0:0:0:1

spring:
  application:
    name: "gateway-service"
  cloud:
    consul:
      host: localhost
      port: 8500

      config:

        enabled: false

resilience4j:
  circuitbreaker:
    instances:
      accountCircuitBreaker:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true
  timelimiter:
    instances:
      accountCircuitBreaker:
        timeoutDuration: 2s

